### ISSUE TITLE
Can't compile L4D2 Stats

### ISSUE THREAD

**Issue by qwsrkiwi** [graviti666/l4d2-survival#1]
I can't compile l4d2_stats.sp because I am missing the l4d2stats.inc, which is not provided in the Git. Tried searching for it on SourceMod and AlliedModders with no results.

Could you please provide the l4d2stats.inc file so that it can be compiled?

**Comment by graviti666** [comment]
Thank you, forgot about it since there was the compiled version already, added the include(s).
